### ISSUE TITLE
Hiya 

### ISSUE THREAD

**Issue by emachala** [YggdrasiI/TinyPrint#4]
Trying to get my B9 working without a laptop tethered with your TinyPrint, installed all depends required on git and compiled onion on RPI2 successfully... when i try and make your code i get this error at 5%.. is it because of signal.boost to signal.boost2 issue?  any help.. I love to get this working free up my laptop..

here is my make error   

`[  0%] Built target htmlfolder
[  5%] Building CXX object src/CMakeFiles/server.dir/OnionServer.cpp.o
In file included from /home/ubuntu/TinyPrint/include/B9CreatorSettings.h:13:0,
                 from /home/ubuntu/TinyPrint/src/OnionServer.cpp:20:
/usr/include/boost/signal.hpp:17:4: warning: #warning "Boost.Signals is no longer being maintained and is now deprecated. Please switch to Boost.Signals2. To disable this warning message, define BOOST_SIGNALS_NO_DEPRECATION_WARNING." [-Wcpp]
 #  warning                  "Boost.Signals is no longer being maintained and is now deprecated. Please switch to Boost.Signals2. To disable this warning message, define BOOST_SIGNALS_NO_DEPRECATION_WARNING."
    ^
In file included from /home/ubuntu/TinyPrint/lib/onion/include/onion/onion.hpp:29:0,
                 from /home/ubuntu/TinyPrint/include/B9CreatorSettings.h:9,
                 from /home/ubuntu/TinyPrint/src/OnionServer.cpp:20:
/home/ubuntu/TinyPrint/lib/onion/include/onion/listen_point.hpp:37:9: error: expected nested-name-specifier before 'internal_pointer'
   using internal_pointer = std::unique_ptr<onion_listen_point, decltype(onion_listen_point_free)*>;
         ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/listen_point.hpp:37:9: error: using-declaration for non-member at class scope
/home/ubuntu/TinyPrint/lib/onion/include/onion/listen_point.hpp:37:26: error: expected ';' before '=' token
   using internal_pointer = std::unique_ptr<onion_listen_point, decltype(onion_listen_point_free)*>;
                          ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/listen_point.hpp:37:26: error: expected unqualified-id before '=' token
/home/ubuntu/TinyPrint/lib/onion/include/onion/listen_point.hpp:38:3: error: 'internal_pointer' does not name a type
   internal_pointer ptr;
   ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/listen_point.hpp:48:26: error: expected ',' or '...' before '&&' token
   ListenPoint(ListenPoint&& other) : ptr { std::move(other.ptr) }
                          ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/listen_point.hpp:48:34: error: invalid constructor; you probably meant 'Onion::ListenPoint (const Onion::ListenPoint&)'
   ListenPoint(ListenPoint&& other) : ptr { std::move(other.ptr) }
                                  ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/listen_point.hpp:49:3: error: expected unqualified-id before '{' token
   {}
   ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/listen_point.hpp: In constructor 'Onion::ListenPoint::ListenPoint()':
/home/ubuntu/TinyPrint/lib/onion/include/onion/listen_point.hpp:41:6: error: class 'Onion::ListenPoint' does not have any field named 'ptr'
    : ptr(onion_listen_point_new(), onion_listen_point_free)
      ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/listen_point.hpp: In constructor 'Onion::ListenPoint::ListenPoint(onion_listen_point*)':
/home/ubuntu/TinyPrint/lib/onion/include/onion/listen_point.hpp:45:6: error: class 'Onion::ListenPoint' does not have any field named 'ptr'
    : ptr(lp, [](onion_listen_point*) { return; })
      ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/listen_point.hpp:45:48: warning: lambda expressions only available with -std=c++11 or -std=gnu++11 [enabled by default]
    : ptr(lp, [](onion_listen_point*) { return; })
                                                ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/listen_point.hpp: In member function 'void Onion::ListenPoint::release()':
/home/ubuntu/TinyPrint/lib/onion/include/onion/listen_point.hpp:55:4: error: 'ptr' was not declared in this scope
    ptr.reset(nullptr);
    ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/listen_point.hpp:55:14: error: 'nullptr' was not declared in this scope
    ptr.reset(nullptr);
              ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/listen_point.hpp: In member function 'onion_listen_point* Onion::ListenPoint::c_handler() const':
/home/ubuntu/TinyPrint/lib/onion/include/onion/listen_point.hpp:61:50: error: 'ptr' was not declared in this scope
   onion_listen_point* c_handler() const { return ptr.get(); }
                                                  ^
In file included from /home/ubuntu/TinyPrint/lib/onion/include/onion/onion.hpp:30:0,
                 from /home/ubuntu/TinyPrint/include/B9CreatorSettings.h:9,
                 from /home/ubuntu/TinyPrint/src/OnionServer.cpp:20:
/home/ubuntu/TinyPrint/lib/onion/include/onion/handler.hpp: At global scope:
/home/ubuntu/TinyPrint/lib/onion/include/onion/handler.hpp:51:32: warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11 [enabled by default]
   HandlerBase(HandlerBase &) = delete;
                                ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/handler.hpp:52:44: warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11 [enabled by default]
   HandlerBase &operator=(HandlerBase &o) = delete;
                                            ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/handler.hpp:58:3: error: 'unique_ptr' in namespace 'std' does not name a type
   std::unique_ptr<HandlerBase> ptr;
   ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/handler.hpp:64:26: error: expected ')' before '<' token
   Handler(std::unique_ptr<T> &&o){
                          ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/handler.hpp:69:33: warning: variadic templates only available with -std=c++11 or -std=gnu++11 [enabled by default]
   template<typename T, typename ...Args>
                                 ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/handler.hpp:70:10: error: 'unique_ptr' in namespace 'std' does not name a type
   static std::unique_ptr<T> make(Args&&... args){
          ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/handler.hpp: In constructor 'Onion::Handler::Handler(Onion::HandlerBase*)':
/home/ubuntu/TinyPrint/lib/onion/include/onion/handler.hpp:61:4: error: 'ptr' was not declared in this scope
    ptr=std::unique_ptr<HandlerBase>(o);
    ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/handler.hpp:61:8: error: 'unique_ptr' is not a member of 'std'
    ptr=std::unique_ptr<HandlerBase>(o);
        ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/handler.hpp:61:35: error: expected primary-expression before '>' token
    ptr=std::unique_ptr<HandlerBase>(o);
                                   ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/handler.hpp: In member function 'Onion::HandlerBase* Onion::Handler::release()':
/home/ubuntu/TinyPrint/lib/onion/include/onion/handler.hpp:67:34: error: 'ptr' was not declared in this scope
   HandlerBase *release(){ return ptr.release(); }
                                  ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/handler.hpp: At global scope:
/home/ubuntu/TinyPrint/lib/onion/include/onion/handler.hpp:119:11: error: 'function' in namespace 'std' does not name a type
   typedef std::function<onion_connection_status (Onion::Request&,Onion::Response&)> fn_t;
           ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/handler.hpp:121:3: error: 'fn_t' does not name a type
   fn_t fn;
   ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/handler.hpp:123:24: error: expected ')' before '_fn'
   HandlerFunction(fn_t _fn) : fn(_fn){}
                        ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/handler.hpp: In member function 'virtual onion_connection_status Onion::HandlerFunction::operator()(Onion::Request&, Onion::Response&)':
/home/ubuntu/TinyPrint/lib/onion/include/onion/handler.hpp:125:22: error: 'fn' was not declared in this scope
    return fn(req, res);
                      ^
In file included from /home/ubuntu/TinyPrint/include/B9CreatorSettings.h:9:0,
                 from /home/ubuntu/TinyPrint/src/OnionServer.cpp:20:
/home/ubuntu/TinyPrint/lib/onion/include/onion/onion.hpp: At global scope:
/home/ubuntu/TinyPrint/lib/onion/include/onion/onion.hpp:224:88: error: expected ',' or '...' before '&&' token
   void addListenPoint(const std::string& hostname, const std::string& port, ListenPoint&& protocol) {
                                                                                        ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/onion.hpp: In member function 'void Onion::Onion::setRootHandler(Onion::Handler)':
/home/ubuntu/TinyPrint/lib/onion/include/onion/onion.hpp:124:55: error: 'move' is not a member of 'std'
    onion_set_root_handler(ptr, onion_handler_cpp_to_c(std::move(handler)));
                                                       ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/onion.hpp: In member function 'void Onion::Onion::setInternalErrorHandler(Onion::Handler)':
/home/ubuntu/TinyPrint/lib/onion/include/onion/onion.hpp:131:65: error: 'move' is not a member of 'std'
    onion_set_internal_error_handler(ptr, onion_handler_cpp_to_c(std::move(handler)));
                                                                 ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/onion.hpp: In member function 'void Onion::Onion::setPort(int)':
/home/ubuntu/TinyPrint/lib/onion/include/onion/onion.hpp:148:25: error: 'to_string' is not a member of 'std'
    std::string port_str=std::to_string(port);
                         ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/onion.hpp: In member function 'void Onion::Onion::addListenPoint(const string&, const string&, Onion::ListenPoint)':
/home/ubuntu/TinyPrint/lib/onion/include/onion/onion.hpp:225:64: error: 'protocol' was not declared in this scope
    onion_add_listen_point(ptr, hostname.c_str(), port.c_str(), protocol.c_handler());
                                                                ^
In file included from /home/ubuntu/TinyPrint/lib/onion/include/onion/request.hpp:27:0,
                 from /home/ubuntu/TinyPrint/include/B9CreatorSettings.h:11,
                 from /home/ubuntu/TinyPrint/src/OnionServer.cpp:20:
/home/ubuntu/TinyPrint/lib/onion/include/onion/dict.hpp: At global scope:
/home/ubuntu/TinyPrint/lib/onion/include/onion/dict.hpp:49:9: error: expected nested-name-specifier before 'internal_pointer'
   using internal_pointer = std::unique_ptr<onion_dict, decltype(onion_dict_free)*>;
         ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/dict.hpp:49:9: error: using-declaration for non-member at class scope
/home/ubuntu/TinyPrint/lib/onion/include/onion/dict.hpp:49:26: error: expected ';' before '=' token
   using internal_pointer = std::unique_ptr<onion_dict, decltype(onion_dict_free)*>;
                          ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/dict.hpp:49:26: error: expected unqualified-id before '=' token
/home/ubuntu/TinyPrint/lib/onion/include/onion/dict.hpp:50:3: error: 'internal_pointer' does not name a type
   internal_pointer ptr;
   ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/dict.hpp:60:27: error: expected ';' at end of member declaration
    virtual ~key_not_found() noexcept;
                           ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/dict.hpp:60:29: error: 'noexcept' does not name a type
    virtual ~key_not_found() noexcept;
                             ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/dict.hpp:61:23: error: expected ';' at end of member declaration
    const char* what() const noexcept;
                       ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/dict.hpp:61:29: error: 'noexcept' does not name a type
    const char* what() const noexcept;
                             ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/dict.hpp:60:12: error: looser throw specifier for 'virtual Onion::Dict::key_not_found::~key_not_found()'
    virtual ~key_not_found() noexcept;
            ^
In file included from /usr/include/c++/4.8/ios:39:0,
                 from /usr/include/c++/4.8/ostream:38,
                 from /usr/include/c++/4.8/iostream:39,
                 from /home/ubuntu/TinyPrint/src/OnionServer.cpp:8:
/usr/include/c++/4.8/exception:64:13: error:   overriding 'virtual std::exception::~exception() throw ()'
     virtual ~exception() _GLIBCXX_USE_NOEXCEPT;
             ^
In file included from /home/ubuntu/TinyPrint/lib/onion/include/onion/request.hpp:27:0,
                 from /home/ubuntu/TinyPrint/include/B9CreatorSettings.h:11,
                 from /home/ubuntu/TinyPrint/src/OnionServer.cpp:20:
/home/ubuntu/TinyPrint/lib/onion/include/onion/dict.hpp:61:16: error: looser throw specifier for 'virtual const char* Onion::Dict::key_not_found::what() const'
    const char* what() const noexcept;
                ^
In file included from /usr/include/c++/4.8/ios:39:0,
                 from /usr/include/c++/4.8/ostream:38,
                 from /usr/include/c++/4.8/iostream:39,
                 from /home/ubuntu/TinyPrint/src/OnionServer.cpp:8:
/usr/include/c++/4.8/exception:68:25: error:   overriding 'virtual const char* std::exception::what() const throw ()'
     virtual const char* what() const _GLIBCXX_USE_NOEXCEPT;
                         ^
In file included from /home/ubuntu/TinyPrint/lib/onion/include/onion/request.hpp:27:0,
                 from /home/ubuntu/TinyPrint/include/B9CreatorSettings.h:11,
                 from /home/ubuntu/TinyPrint/src/OnionServer.cpp:20:
/home/ubuntu/TinyPrint/lib/onion/include/onion/dict.hpp:76:13: error: expected ',' or '...' before '&&' token
    lock(lock&& l) : dict(l.dict) { l.dict = nullptr; }
             ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/dict.hpp:76:17: error: invalid constructor; you probably meant 'Onion::Dict::lock (const Onion::Dict::lock&)'
    lock(lock&& l) : dict(l.dict) { l.dict = nullptr; }
                 ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/dict.hpp:99:29: error: expected ')' before '<' token
   Dict(std::initializer_list<std::initializer_list<std::string>> &&init);
                             ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/dict.hpp:158:34: error: expected ';' at end of member declaration
   bool has(const std::string &k) const noexcept;
                                  ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/dict.hpp:158:40: error: 'noexcept' does not name a type
   bool has(const std::string &k) const noexcept;
                                        ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/dict.hpp:165:38: error: expected ';' at end of member declaration
   Dict getDict(const std::string &k) const noexcept;
                                      ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/dict.hpp:165:44: error: 'noexcept' does not name a type
   Dict getDict(const std::string &k) const noexcept;
                                            ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/dict.hpp:173:68: error: expected ';' at end of member declaration
   std::string get(const std::string &k, const std::string &def="") const noexcept
                                                                    ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/dict.hpp:173:74: error: 'noexcept' does not name a type
   std::string get(const std::string &k, const std::string &def="") const noexcept
                                                                          ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/dict.hpp:185:77: error: expected ';' at end of member declaration
   Dict &add(const std::string &k, const std::string &v, int flags=OD_DUP_ALL) noexcept;
                                                                             ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/dict.hpp:185:79: error: 'noexcept' does not name a type
   Dict &add(const std::string &k, const std::string &v, int flags=OD_DUP_ALL) noexcept;
                                                                               ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/dict.hpp:190:70: error: expected ';' at end of member declaration
   Dict &add(const std::string &k, const Dict &v, int flags=OD_DUP_ALL) noexcept;
                                                                      ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/dict.hpp:190:72: error: 'noexcept' does not name a type
   Dict &add(const std::string &k, const Dict &v, int flags=OD_DUP_ALL) noexcept;
                                                                        ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/dict.hpp:195:36: error: expected ';' at end of member declaration
   Dict &remove(const std::string &k) noexcept;
                                    ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/dict.hpp:195:38: error: 'noexcept' does not name a type
   Dict &remove(const std::string &k) noexcept;
                                      ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/dict.hpp:200:18: error: expected ';' at end of member declaration
   size_t count() const noexcept
                  ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/dict.hpp:200:24: error: 'noexcept' does not name a type
   size_t count() const noexcept
                        ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/dict.hpp:208:24: error: expected ';' at end of member declaration
   std::string toJSON() const noexcept;
                        ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/dict.hpp:208:30: error: 'noexcept' does not name a type
   std::string toJSON() const noexcept;
                              ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/dict.hpp:215:51: error: expected ';' at end of member declaration
   static Dict fromJSON(const std::string &jsondata) noexcept;
                                                   ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/dict.hpp:215:53: error: 'noexcept' does not name a type
   static Dict fromJSON(const std::string &jsondata) noexcept;
                                                     ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/dict.hpp:222:41: error: expected ';' at end of member declaration
   Dict &merge(const ::Onion::Dict &other) noexcept;
                                         ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/dict.hpp:222:43: error: 'noexcept' does not name a type
   Dict &merge(const ::Onion::Dict &other) noexcept;
                                           ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/dict.hpp:245:19: error: expected ';' at end of member declaration
   lock readLock() const noexcept
                   ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/dict.hpp:245:25: error: 'noexcept' does not name a type
   lock readLock() const noexcept
                         ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/dict.hpp:256:20: error: expected ';' at end of member declaration
   lock writeLock() const noexcept
                    ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/dict.hpp:256:26: error: 'noexcept' does not name a type
   lock writeLock() const noexcept
                          ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/dict.hpp:265:27: error: expected ';' at end of member declaration
   onion_dict *c_handler() const noexcept;
                           ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/dict.hpp:265:33: error: 'noexcept' does not name a type
   onion_dict *c_handler() const noexcept;
                                 ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/dict.hpp: In constructor 'Onion::Dict::Dict()':
/home/ubuntu/TinyPrint/lib/onion/include/onion/dict.hpp:104:15: error: class 'Onion::Dict' does not have any field named 'ptr'
      Dict() : ptr { onion_dict_new(), &onion_dict_free } {}
               ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/dict.hpp:104:15: warning: extended initializer lists only available with -std=c++11 or -std=gnu++11 [enabled by default]
/home/ubuntu/TinyPrint/lib/onion/include/onion/dict.hpp: In member function 'std::string Onion::Dict::operator[](const string&) const':
/home/ubuntu/TinyPrint/lib/onion/include/onion/dict.hpp:130:35: error: 'ptr' was not declared in this scope
    const char* r = onion_dict_get(ptr.get(), k.c_str());
                                   ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/dict.hpp:132:11: warning: extended initializer lists only available with -std=c++11 or -std=gnu++11 [enabled by default]
     throw key_not_found { k };
           ^
In file included from /home/ubuntu/TinyPrint/include/B9CreatorSettings.h:11:0,
                 from /home/ubuntu/TinyPrint/src/OnionServer.cpp:20:
/home/ubuntu/TinyPrint/lib/onion/include/onion/request.hpp: In member function 'const string Onion::Request::post(const string&, const string&) const':
/home/ubuntu/TinyPrint/lib/onion/include/onion/request.hpp:75:9: error: 'r' does not name a type
    auto r=onion_request_get_post(ptr, key.c_str());
         ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/request.hpp:76:9: error: 'r' was not declared in this scope
    if (!r)
         ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/request.hpp:78:11: error: 'r' was not declared in this scope
    return r;
           ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/request.hpp: In member function 'const string Onion::Request::query(const string&, const string&) const':
/home/ubuntu/TinyPrint/lib/onion/include/onion/request.hpp:94:9: error: 'r' does not name a type
    auto r=onion_request_get_query(ptr, key.c_str());
         ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/request.hpp:95:9: error: 'r' was not declared in this scope
    if (!r)
         ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/request.hpp:97:11: error: 'r' was not declared in this scope
    return r;
           ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/request.hpp: In member function 'const string Onion::Request::session(const string&, const string&) const':
/home/ubuntu/TinyPrint/lib/onion/include/onion/request.hpp:115:9: error: 'r' does not name a type
    auto r=onion_request_get_session(ptr, key.c_str());
         ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/request.hpp:116:9: error: 'r' was not declared in this scope
    if (!r)
         ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/request.hpp:118:11: error: 'r' was not declared in this scope
    return r;
           ^
In file included from /home/ubuntu/TinyPrint/include/B9CreatorSettings.h:11:0,
                 from /home/ubuntu/TinyPrint/src/OnionServer.cpp:20:
/home/ubuntu/TinyPrint/lib/onion/include/onion/request.hpp: In member function 'const string Onion::Request::cookies(const string&, const string&) const':
/home/ubuntu/TinyPrint/lib/onion/include/onion/request.hpp:186:9: error: 'r' does not name a type
    auto r=onion_request_get_cookie(ptr, key.c_str());
         ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/request.hpp:187:9: error: 'r' was not declared in this scope
    if (!r)
         ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/request.hpp:189:11: error: 'r' was not declared in this scope
    return r;
           ^
In file included from /home/ubuntu/TinyPrint/include/OnionServer.h:20:0,
                 from /home/ubuntu/TinyPrint/src/OnionServer.cpp:21:
/home/ubuntu/TinyPrint/lib/onion/include/onion/url.hpp: At global scope:
/home/ubuntu/TinyPrint/lib/onion/include/onion/url.hpp:70:9: error: expected nested-name-specifier before 'internal_pointer'
   using internal_pointer = std::unique_ptr<onion_url, decltype(onion_url_free)*>;
         ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/url.hpp:70:9: error: using-declaration for non-member at class scope
/home/ubuntu/TinyPrint/lib/onion/include/onion/url.hpp:70:26: error: expected ';' before '=' token
   using internal_pointer = std::unique_ptr<onion_url, decltype(onion_url_free)*>;
                          ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/url.hpp:70:26: error: expected unqualified-id before '=' token
/home/ubuntu/TinyPrint/lib/onion/include/onion/url.hpp:71:3: error: 'internal_pointer' does not name a type
   internal_pointer ptr;
   ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/url.hpp:94:11: error: expected ',' or '...' before '&&' token
   Url(Url &&o);
           ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/url.hpp:94:14: error: invalid constructor; you probably meant 'Onion::Url (const Onion::Url&)'
   Url(Url &&o);
              ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/url.hpp:96:16: warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11 [enabled by default]
   Url(Url &) = delete;
                ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/url.hpp:97:28: warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11 [enabled by default]
   Url &operator=(Url &o) = delete;
                            ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/url.hpp:109:44: error: expected ',' or '...' before '&&' token
   Url& add(const std::string &url, Handler &&h);
                                            ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/url.hpp:123:53: error: 'Onion::HandlerFunction::fn_t' has not been declared
   Url& add(const std::string &url, HandlerFunction::fn_t fn);
                                                     ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/url.hpp: In member function 'Onion::Url& Onion::Url::add(const string&, T*, onion_connection_status (T::*)(Onion::Request&, Onion::Response&))':
/home/ubuntu/TinyPrint/lib/onion/include/onion/url.hpp:147:28: error: expected primary-expression before '&&' token
    return add(url, (Handler&&)Handler::make<HandlerMethod<T>>(o,fn));
                            ^
/home/ubuntu/TinyPrint/lib/onion/include/onion/url.hpp:147:30: error: expected primary-expression before ')' token
    return add(url, (Handler&&)Handler::make<HandlerMethod<T>>(o,fn));
                              ^
make[2]: *** [src/CMakeFiles/server.dir/OnionServer.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/server.dir/all] Error 2
make: *** [all] Error 2
`

**Comment by YggdrasiI** [comment]
Hello emachala,

I can reproduce this error, too. The reason is a missing compiling flag. It seems that now  "-std=gnu++11" (or similar) is required to select the correct C++ standard.

I'm working on a commit which should fix this compiling issue, switches to boost:signals2 and resolve some other library dependencies.

Regards Olaf

P.S. Due non-relevant reasons I does not follow the development of the B9Creator printer for a while. Thus, I do not know if TinyPrint still works with the current firmware of the printer. My last update was on version  DLP3DPAPI 1.1, Dec 2012!
Nevertheless I'm interested to keep the software run-able (if the effort is acceptable) :-)

**Comment by emachala** [comment]
Awesome thanks, Im in a similar boat, i have modified my b9 from a sliding vat to and tilt system..., changing only a tiny bit of firmware on b9c... so i would need to change a tiny bit to make Tinyprint work with my setup... Just some speed adjustments to shutter open close which is now a TILT.

 But freeing up my laptop for printing with TINYPrint is my goal... 

Thanks again im really not the familiar with boost.signals

**Comment by YggdrasiI** [comment]
I've pushed now a new version. It should be compile, now. If you put a file into [build dir]/job_files (example file attached) it should be available in the drop down selection on localhost:9090.

[puzzle.svg.zip](https://github.com/YggdrasiI/TinyPrint/files/221771/puzzle.svg.zip)

**Comment by emachala** [comment]
Cool, can't wait to try... still showing me last commit was Latest commit 09c800b  on Feb 13, 2014..

maybe its not up yet?

**Comment by emachala** [comment]
cache it was :P

**Comment by emachala** [comment]
Thanks a bunch gonna move it to my printer area compiled correctly :+1:

**Comment by YggdrasiI** [comment]
I tried it on my RPi3, too and found an other issue. If localhost:9090/files.js is incomplete ('json_job_files =') try to set LC_ALL before you start TinyPrint, i.e.
``export LC_ALL="en_GB.UTF-8"``

With this change, I could start TinyPrint with ``sudo bin/start.sh pi32``, load a job file and press on 'Toggle display'
